# Generated by Django 6.1.1 on 2026-09-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Уникальное название: ATTACK, BLOCK')),
                ('name', models.CharField(max_length=50, verbose_name='Название действия')),
            ],
            options={
                'verbose_name': 'Действие статистики',
                'verbose_name_plural': 'Действия статистики',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100, verbose_name='Название соперника')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.team', verbose_name='Наша команда')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(verbose_name='Номер партии')),
                ('serving_team', models.CharField(choices=[('HOME', 'Мы'), ('AWAY', 'Соперник')], default='HOME', max_length=10, verbose_name='Подающая команда')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='score.match', verbose_name='Матч')),
                ('p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p1', to='players.player', verbose_name='Зона 1 (подача)')),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p2', to='players.player', verbose_name='Зона 2')),
                ('p3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p3', to='players.player', verbose_name='Зона 3')),
                ('p4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p4', to='players.player', verbose_name='Зона 4')),
                ('p5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p5', to='players.player', verbose_name='Зона 5')),
                ('p6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p6', to='players.player', verbose_name='Зона 6')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'unique_together': {('match', 'set_number')},
            },
        ),
        migrations.CreateModel(
            name='StatGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, verbose_name='Символ оценки (#, +, !, -, =)')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('default_weight', models.FloatField(default=1.0, verbose_name='Вес по умолчанию (например, 0.5)')),
                ('point_effect', models.IntegerField(choices=[(-1, 'Очко сопернику'), (0, 'Без очка (мяч в игре)'), (1, 'Очко нашей команде')], default=0, verbose_name='Влияние на счёт')),
                ('is_simple', models.BooleanField(default=False, verbose_name='Относится к простой статистике')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='score.stataspect', verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценок',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='Вес действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('p1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_p1', to='players.player', verbose_name='Зона 1')),
                ('p2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_p2', to='players.player', verbose_name='Зона 2')),
                ('p3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_p3', to='players.player', verbose_name='Зона 3')),
                ('p4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_p4', to='players.player', verbose_name='Зона 4')),
                ('p5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_p5', to='players.player', verbose_name='Зона 5')),
                ('p6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_p6', to='players.player', verbose_name='Зона 6')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='players.player', verbose_name='Игрок (пусто, если ошибка соперника)')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='score.set', verbose_name='Партия')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='score.statgrade', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Событие матча',
                'verbose_name_plural': 'События матчей',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('ACCEPTED', 'Принято')], default='ACCEPTED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дружба',
                'verbose_name_plural': 'Дружба',
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
