# Generated by Django 6.1.1 on 2026-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('ACCEPTED', 'Принято')], default='ACCEPTED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Дружба',
                'verbose_name_plural': 'Дружба',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100, verbose_name='Название соперника')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='Вес действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
            ],
            options={
                'verbose_name': 'Событие матча',
                'verbose_name_plural': 'События матчей',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(verbose_name='Номер партии')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
            },
        ),
        migrations.CreateModel(
            name='StatAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Уникальный код')),
                ('name', models.CharField(max_length=50, verbose_name='Название действия')),
            ],
            options={
                'verbose_name': 'Действие статистики',
                'verbose_name_plural': 'Действия статистики',
            },
        ),
        migrations.CreateModel(
            name='StatGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, verbose_name='Символ оценки (#, +, !, -, =)')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('default_weight', models.FloatField(default=1.0, verbose_name='Вес по умолчанию (например, 0.5)')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценок',
            },
        ),
    ]
