# Generated by Django 6.1.1 on 2026-09-25 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100, verbose_name='Название соперника')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='StatAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Уникальный код')),
                ('name', models.CharField(max_length=50, verbose_name='Название действия')),
            ],
            options={
                'verbose_name': 'Действие статистики',
                'verbose_name_plural': 'Действия статистики',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО игрока')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_players', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(verbose_name='Номер партии')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='score.match', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'unique_together': {('match', 'set_number')},
            },
        ),
        migrations.CreateModel(
            name='StatGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5, verbose_name='Символ оценки (#, +, !, -, =)')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('default_weight', models.FloatField(default=1.0, verbose_name='Вес по умолчанию (например, 0.5)')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='score.stataspect', verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Критерий оценки',
                'verbose_name_plural': 'Критерии оценок',
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='Вес действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='score.player', verbose_name='Игрок (пусто, если ошибка соперника)')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='score.set', verbose_name='Партия')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='score.statgrade', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Событие матча',
                'verbose_name_plural': 'События матчей',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='score.team', verbose_name='Наша команда'),
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Игровой номер в команде')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='score.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='score.team')),
            ],
            options={
                'verbose_name': 'Игрок в команде',
                'verbose_name_plural': 'Составы команд',
                'unique_together': {('team', 'number'), ('team', 'player')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', through='score.TeamPlayer', to='score.player', verbose_name='Состав команды'),
        ),
    ]
