# Generated by Django 6.1.1 on 2026-09-25 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0002_initial'),
        ('score', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.team', verbose_name='Наша команда'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='players.player', verbose_name='Игрок (пусто, если ошибка соперника)'),
        ),
        migrations.AddField(
            model_name='set',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='score.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='score.set', verbose_name='Партия'),
        ),
        migrations.AddField(
            model_name='statgrade',
            name='aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='score.stataspect', verbose_name='Действие'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='score.statgrade', verbose_name='Оценка'),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('user', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='set',
            unique_together={('match', 'set_number')},
        ),
    ]
