# Generated by Django 6.1.1 on 2026-09-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statgrade',
            name='point_effect',
            field=models.IntegerField(choices=[(-1, 'Очко сопернику'), (0, 'Без очка (мяч в игре)'), (1, 'Очко нашей команде')], default=0, verbose_name='Влияние на счёт'),
        ),
        migrations.AlterField(
            model_name='stataspect',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Уникальное название: ATTACK, BLOCK'),
        ),
    ]
