# Generated by Django 6.1.1 on 2026-09-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_statgrade_point_effect_alter_stataspect_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='away_score',
            field=models.FloatField(default=0.0, verbose_name='Очки противника'),
        ),
        migrations.AddField(
            model_name='set',
            name='home_score',
            field=models.FloatField(default=0.0, verbose_name='Очки наши'),
        ),
    ]
