# Generated by Django 6.1.1 on 2026-09-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_set_away_score_set_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='serving_team',
            field=models.CharField(choices=[('HOME', 'Мы'), ('AWAY', 'Соперник')], default='HOME', max_length=10, verbose_name='Подающая команда'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(verbose_name='Дата проведения'),
        ),
    ]
