# Generated by Django 6.1.1 on 2026-09-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
        ('score', '0005_set_serving_team_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Партия завершена'),
        ),
        migrations.AddField(
            model_name='set',
            name='p1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p1', to='players.player', verbose_name='Зона 1 (подача)'),
        ),
        migrations.AddField(
            model_name='set',
            name='p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p2', to='players.player', verbose_name='Зона 2'),
        ),
        migrations.AddField(
            model_name='set',
            name='p3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p3', to='players.player', verbose_name='Зона 3'),
        ),
        migrations.AddField(
            model_name='set',
            name='p4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p4', to='players.player', verbose_name='Зона 4'),
        ),
        migrations.AddField(
            model_name='set',
            name='p5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p5', to='players.player', verbose_name='Зона 5'),
        ),
        migrations.AddField(
            model_name='set',
            name='p6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_p6', to='players.player', verbose_name='Зона 6'),
        ),
        migrations.AddField(
            model_name='statgrade',
            name='is_simple',
            field=models.BooleanField(default=False, verbose_name='Относится к простой статистике'),
        ),
    ]
